### ISSUE TITLE
Very high frequency data (such as every minute or every hour)

### ISSUE THREAD

**Issue by ritkum** [tgsmith61591/pyramid#12]

**Comment by tgsmith61591** [comment]
Can you provide a minimal reproducible example? Code/data that we can run on our end?

**Comment by ritkum** [comment]
I tried running it over the data set with a frequency of every 5 seconds.

**Comment by tgsmith61591** [comment]
Thanks for pointing this out. Can you please provide the data you're using, if you're able, and the code you're running? We need to have a minimal reproducible example to be able to debug this.

**Comment by tgsmith61591** [comment]
`pyramid` is designed to behave like R's `auto.arima`. So if you're able to do it there, the hope is you'd be able to do it here. In R, the frequency (for ARIMA purposes, it will be the seasonality parameter, `m`) is the number of observations per cycle. See [this answer](https://stats.stackexchange.com/questions/120806/frequency-value-for-seconds-minutes-intervals-data-in-r) to better understand, but generally you'd use the following options:

```python
Data      frequency
Annual            1
Quarterly         4
Monthly          12
Weekly           52
```

Therefore, daily periodicity would be 365. Using the same formula, hourly periodicity would ostensibly be 365 * 24 (8760), minutely would be 365 * 24 * 60 (525600), etc... Conceivably you should be able to fit data with a higher frequency, such as you've mentioned. In fact, the code *does* permit this [in this block](https://github.com/tgsmith61591/pyramid/blob/master/pyramid/arima/seasonality.py#L203):

```python
if m <= 12:
    return int(chstat > crit_vals[m - 2])  # R does m - 1...
if m == 24:
    return int(chstat > 5.098624)
if m == 52:
    return int(chstat > 10.341416)
if m == 365:
    return int(chstat > 65.44445)

# RIGHT HERE for all other m values, high or low
return int(chstat > 0.269 * (m ** 0.928))
```
For us to know that this does **not** work, we'd need a minimum reproducible example with data and code to see where it's failing or whether the results are unexpected (and, for that matter, *why* they're unexpected).

Here's the rub, though. If your `m` parameter is *that high*, you need to have >= that number of samples for your fit, which is expected behavior (in fact, that is how R behaves to my knowledge). Alternatively, if you only have data for a day, for example, you'd have to determine the `m` that divides your sample into the expected seasons. That's the best I can guide you without data and code.

Adding @charlesdrotar so we're both notified for future updates.

**Comment by ritkum** [comment]
I have a seasonal time-series data set which comprises of 2 months of data. Now if I mention the frequency as "2 min" or "365x24x30" then it tries to divide the dataset with that frequency. But my data set is just for 2 months and obviously, it has way lesser values than the freq. I have attached a sample data set here for your reference. Please rename the file as .csv
[dummy_data.txt](https://github.com/tgsmith61591/pyramid/files/1170278/dummy_data.txt)

**Comment by tgsmith61591** [comment]
I think I understand your confusion, now. So even though your data has a 2-minute interval, your *seasonality __is not__ necessarily that frequent*. I put together [an ipython notebook](https://github.com/tgsmith61591/pyramid/blob/issue-12/examples/issue12/issue-12.ipynb) on a feature branch for you to visualize the seasonality of the data (which appears to be much less frequent than every 2 minutes).

Once you determine your seasonality (`m` term), you can start tinkering with other parameters in the `auto_arima` function. Note that it appears you have 3 seasons over the window of your data, and potentially 18 over the course of a year... proceed accordingly. Hope this helps!

**Comment by AmberSJones** [comment]
I am getting started using pmdarima and trying to resolve some confusion with m. Rather than ask a new question, I'm appending to this related question and hoping you can clarify, @tgsmith61591.

I am working with datasets of environmental observations of 15-minute intervals that exhibit strong daily trends. I'm trying to understand what value of m to use. Is m necessarily based on a full period of a year (as indicated above)? In that case, m = 365x24x4. However, I'm not interested in the value exactly one year ago, I'm interested in the value one day ago, so I would assume that the seasonal period is one day, corresponding to an m = 24x4. This is consistent with another definition I have of m as "the number of time steps for a single seasonal period". 

When I try using auto_arima for a year of data with m=96, the process gets killed. It takes 2700 s for ~2 days of data. My intent is to run the algorithm for a year of data at a time. How can I make this computationally feasible?
