### ISSUE TITLE
cannot import name 'C_Approx'

### ISSUE THREAD

**Issue by SomasishGhosh** [tgsmith61591/pyramid#21]
#### Description
Earlier a similar issue was raised with a clarification that it would be solved when pyramid has a pip installation. After installing I am facing the same problems.

#### Steps/Code to Reproduce
from pyramid.arima install auto_arima

File "C:\Users\somasishg\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyramid\arima\approx.py", line 18, in <module>
    from pyramid.arima._arima import C_Approx

ImportError: cannot import name 'C_Approx'

I have tried from pyramid.arima import C_Approx but issue remains.

**Comment by tgsmith61591** [comment]
C_approx is compiled C code by the time you install the package. You should
not be able to import that. To test that it built properly, you can run:

from pyramid.arima import auto_arima

That module uses the compiled C but you will not be able to import it
directly.

**Comment by SomasishGhosh** [comment]
I tried running:
from pyramid.arima import auto_arima

Unfortunately, it is giving the error :
ImportError: cannot import name 'C_Approx'

**Comment by tgsmith61591** [comment]
Please include pyramid version as well as pip output. I recommend trying a
fresh install from a new conda environment or virtualenv so you are certain
pyramid is not already in your path somewhere.

On Dec 19, 2017 5:54 AM, "SomasishGhosh" <notifications@github.com> wrote:

I tried running:
from pyramid.arima import auto_arima

Unfortunately, it is giving the error :

ImportError: cannot import name 'C_Approx'

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tgsmith61591/pyramid/issues/21#issuecomment-352728469>,
or mute the thread

**Comment by tgsmith61591** [comment]
(also platform info—the issues template includes a snippet you should run)

**Comment by SomasishGhosh** [comment]
There was a problem with numpy version. Upgrading numpy solved the issue.
