### ISSUE TITLE
failed install pyramid-arima

### ISSUE THREAD

**Issue by xiaoyTed** [tgsmith61591/pyramid#36]
#### Steps/Code to Reproduce
<!--
pip install pyramid-arima

```
-->

#### Expected Results
<!--install succefully.-->

#### Actual Results
<!-- failed, [winerror 2] ,the system can't find the specified file -->

#### Versions
<!--
Please run the following snippet and paste the output below.
Windows-7-6.1.7601-SP1
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
NumPy 1.15.2
SciPy 1.1.0
Scikit-Learn 0.19.1
Statsmodels 0.9.0
-->


<!-- Thanks for contributing! -->

**Comment by tgsmith61591** [comment]
Can you provide some details...?

**Comment by xiaoyTed** [comment]
I don't what details do you want, below is the error type, showing in prompt


###   **running build_ext
  Building msvcr library: "c:\users\ding.qi\appdata\local\continuum\anaconda3\li
bs\libvcruntime140.a" (from c:\users\ding.qi\appdata\local\continuum\anaconda3\v
cruntime140.dll)
  error: [WinError 2] The system cannot find the file specified**

  ----------------------------------------
  Failed building wheel for pyramid-arima
  Running setup.py clean for pyramid-arima
Failed to build pyramid-arima
Installing collected packages: pyramid-arima
  Running setup.py install for pyramid-arima ... error
   
     ----------------------------------------
Command "c:\users\ding.qi\appdata\local\continuum\anaconda3\python.exe -u -c "im
port setuptools, tokenize;__file__='C:\\Users\\ding.qi\\AppData\\Local\\Temp\\pi
p-install-mqipn26c\\pyramid-arima\\setup.py';f=getattr(tokenize, 'open', open)(_
_file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file
__, 'exec'))" install --record C:\Users\ding.qi\AppData\Local\Temp\pip-record-as
nzqu0f\install-record.txt --single-version-externally-managed --compile" failed
with error code 1 in C:\Users\ding.qi\AppData\Local\Temp\pip-install-mqipn26c\py
ramid-arima\

**Comment by xiaoyTed** [comment]
I use the command 'pip install pyramid-arima' in anaconda prompt, but I fail to install.
And the error type I have copy it.

Windows-7-6.1.7601-SP1
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
NumPy 1.15.2
SciPy 1.1.0
Scikit-Learn 0.19.1
Statsmodels 0.9.0

**Comment by tgsmith61591** [comment]
Try something... what if you try building with 3.5? There are wheels for 3.5--I wonder if since you're on 3.6 and you're having to build from source it's not working for you?

```
$ conda create -n pmdarima --yes python=3.5 scipy numpy scikit-learn pandas statsmodels
$ activate pmdarima
(pmdarima) $ pip install pyramid-arima
```

**Comment by triciascully** [comment]
@tgsmith61591 I'm getting the same issue, error on building wheels, but the issue is:

/anaconda3/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found

I'm building a model on my work system and cannot use 3.5 in our prod environment, what's the workaround for staying in 3.6?

**Comment by tgsmith61591** [comment]
So the 3.5 wheel was a proposed solution because the wheels exist already in PyPi. If you're seeing a 'stdio.h' file not found, that seems like a [separate issue](https://stackoverflow.com/questions/39968458/windows-10-clang-stdio-h-not-found) that's unrelated to the package itself (and because the information I got from OP was scant, I'm guessing his issue is related).

For the next release I'll include 3.6 wheels for Linux, Mac and Windows

**Comment by triciascully** [comment]
Ah, thank you - I've researched the stdio.h file issue and still haven't found a fix yet for me (the link you provided was for Windows users, and I'm fortunately and unfortunately a mac user), so I thought it might be linked to this wheel issue. Looking forward to that next release though -- thanks for all the work on this, it's a great option for us users who are forced to use python instead of R for projects

**Comment by tgsmith61591** [comment]
I'm on a Mac too, so my ability to debug these Windows issues it limited :) You might try updating GCC via homebrew? Of course I'm guessing you've tried all of that...

Stay tuned for the newest version hopefully whenever my schedule allows! Glad to hear it's been a helpful package to date.

**Comment by xiaoyTed** [comment]
I have install the package, but when use it in jupyter notebook, there is still error that can't find"pyramid.arima'.

the code is:
from pyramid.arima import auto_arima


(pmdarima) C:\Users\ding.qi>pip list
Package         Version
--------------- ---------
certifi         2018.8.24
Cython          0.28.5
mkl-fft         1.0.6
mkl-random      1.0.1
numpy           1.15.2
pandas          0.23.4
patsy           0.5.0
pip             10.0.1
pyramid-arima   0.8.1
python-dateutil 2.7.3
pytz            2018.5
scikit-learn    0.20.0
scipy           1.1.0
setuptools      40.2.0
six             1.11.0
statsmodels     0.9.0
wheel           0.31.1
wincertstore    0.2

**Comment by tgsmith61591** [comment]
Willing to bet this is related to #23. See also [this question](https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing) on SO. It's not an installation issue, it's that your Jupyter notebook isn't executing in the same env as your installation

**Comment by xiaoyTed** [comment]
sorry one more question
`I` think the problem is , it's using libraries from default location: //Anaconda3/Lib/site-packages.
I need to have them sourced from `//Anaconda3/envs/pmdissue23/Lib/site-packages.`

hello, how to change the path?

**Comment by tgsmith61591** [comment]
This is getting past the scope of what is related to Pyramid at this point. The anaconda doc is very clear on [how to source environments](https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment). This is also a question you could always ask of [stack overflow](https://stackoverflow.com/questions/20081338/how-to-activate-an-anaconda-environment).

As far as how you use a sourced environment in Jupyter, there's an answer for that [here](https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing).

Since we're no longer working on an issue related to the package, I'm going to close this issue

**Comment by xiaoyTed** [comment]
your information is really helpful, thank you very much

**Comment by tgsmith61591** [comment]
@triciascully #42 includes a 3.6 wheel for Linux!

**Comment by Polinafa** [comment]
For peps looking for a solution. Had the same problem solved it by installing Command Line Tools.

**Comment by VigneshSrinivas** [comment]
Hi,I have an issue in which pyramid-arima is not in the pip-list. Please help me out to add the specific package in the list.

**Comment by VigneshSrinivas** [comment]
Okay, now I have installed pyramid-arima, thanks for  tgsmith61591

**Comment by tgsmith61591** [comment]
@VigneshSrinivas do not install pyramid-arima, install pmdarima. See #34 for an explanation

**Comment by RogerioDataScience** [comment]
tgsmith61591 cara muito obrigado por essas dicas me ajudou muito , não estava conseguindo tambem  fazer a instancia do ARIMA e deu super certo, thanks!!1
